Completed task
olgamorozova1/Automation pull request #1
Opened 2020-09-13 18:41 UTC by olgamorozova1

2020-09-17 19:26 UTC, KirillKarpov requested changes

2020-09-20 19:05 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +class JsonParserTest {
Added two new tests: writeToFileTest and readFromFileTest which contains my own reader and writer.

2020-09-20 19:05 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +    File file;
Added access modifiers.

2020-09-20 19:06 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +    void createdCartWithZeroWeightOfRealItem() {
Fixed weight to zero.

2020-09-20 19:07 UTC, olgamorozova1 commented on src/test/java/shop/CartTest.java
> +    RealItem pen = new RealItem();
Added new tests: deleteRealItemTest and deleteVirtualItemTest.

2020-09-20 19:08 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +    public void testNoSuchFileException() {
Added new test: NoSuchFileExceptionTest with ParameterizedTest and 5 datasets.

2020-09-20 19:09 UTC, olgamorozova1 commented on src/test/java/shop/RealItemTest.java
> +    void setWeight_isObjectCreated_True() {
Deleted this test as it does not have sense. Other tests are named in camel case.

2020-09-20 19:09 UTC, olgamorozova1 commented on src/test/java/shop/RealItemTest.java
> +class RealItemTest {
2 tests deleted.

2020-09-20 19:10 UTC, olgamorozova1 commented on src/test/java/shop/VirtualItemTest.java
> +    @BeforeEach
This test is deleted.

2020-09-20 19:17 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +        assertReflectionEquals(expectedCart, actualCart);
Sorry but I cannot find appropriate method in Junit. We cannot use assertEquals for Objects as we need to compare them by fields not links. We cannot use groupedAssertions and compare by fields as we have getter only for Cart name. Do you mean I have to use Hamcrest assertion libraries and method AssertThat? Could you please give me a hint? :)

2020-09-21 05:54 UTC, olgamorozova1 commented on src/test/java/shop/CartTest.java
> +        assertEquals(133.33, Math.round(actualResult * 100) / 100.0d);
All changes are made in test getTotalPriceTestForAllItems.

2020-10-04 20:24 UTC, KirillKarpov commented on .idea/.gitignore
> +/workspace.xml
I forgot to say that you also need to do additional commit where you remove ./idea and UnitTesting.iml files from repository

2020-10-04 20:29 UTC, KirillKarpov commented on src/test/java/parser/JsonParserTest.java
> +        assertReflectionEquals(expectedCart, actualCart);
It is a trick task :). You are right that assertEquals method should be used. Can we use it there ?

2020-10-04 20:32 UTC, KirillKarpov commented on src/test/java/parser/JsonParserTest.java
> +    File file;
Could you please explain why did you choose public access modifiers? What other can be used there ?

2020-10-05 18:09 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +        assertReflectionEquals(expectedCart, actualCart);
No, we cannot use AssertEquals as methods hashCode() and equals() are not overridden in the Cart class.

2020-10-05 18:25 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +    File file;
I've chosen public as I did not want to create getters/setters for them to avoid extra code, but seems like it is not needed anyway as I do not need the access for them from other classes. So you are right, it is better to make them private.

2020-10-05 19:20 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +    File file;
Made all variables private.

2020-10-05 19:20 UTC, olgamorozova1 commented on src/test/java/shop/CartTest.java
> +        assertEquals(pen.getPrice()+pen.getPrice()*tax+book.getPrice()+book.getPrice()*tax, testCart.getTotalPrice(), 0.001);
Fixed.

2020-10-05 19:21 UTC, olgamorozova1 commented on src/test/java/shop/CartTest.java
> +    void deleteVirtualItemTest() {
Yes, created new test to check Total Price after deleting item: deleteVirtualItemAndCheckTotalPriceTest.

2020-10-05 19:21 UTC, olgamorozova1 commented on src/test/java/shop/CartTest.java
> +    void deleteRealItemTest() {
Yes, created new test to check Total Price after deleting item: deleteRealItemAndCheckTotalPriceTest.

2020-10-05 19:22 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +        assertReflectionEquals(expectedCart, actualCart);
Formatting fixed.

2020-10-05 19:22 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +
Formatting fixed.

2020-10-05 19:23 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTest.java
> +
Formatting fixed.

2020-10-05 19:23 UTC, olgamorozova1 commented on src/test/java/shop/CartTest.java
> +
Formatting fixed.

2020-10-05 19:45 UTC, olgamorozova1 commented on .idea/.gitignore
> +/workspace.xml
Files are removed.

2020-10-07 06:37 UTC, KirillKarpov commented
Looks good for me. You can merge your pull request

2020-10-07 09:33 UTC, KirillKarpov approved these changes

2020-10-07 17:40 UTC, merged