Completed task
olgamorozova1/Automation pull request #2
Opened 2020-10-08 19:06 UTC by olgamorozova1

Task 2

2020-10-11 15:58 UTC, KirillKarpov requested changes

2020-10-11 15:58 UTC, KirillKarpov commented on testng.xml
> +</suite>
The good rule is to have understandable naming for files. Especially when it is testng xml suites. 
Testng, testng1 and etc. don't look clear.
You can names from from xml file such as ExceptionTestWithDifferentParameters, SmokeTestOfCartClass and etc.

2020-10-11 15:58 UTC, KirillKarpov commented on testng3.xml
> +        <parameter name="path" value="src\main\resources\test-cart.json"/>
As I mentioned before , if you want remove dependency on operation system, slash should be used instead of backslash.

2020-10-11 16:01 UTC, KirillKarpov commented
@Parameter looks good as solution for 1 task (.. Exception test with >= 5 datasets).
I would like to ask you also write exception test with >= 5 datasets using @DataProvider from testNG

2020-10-11 16:03 UTC, KirillKarpov requested changes

2020-10-11 16:03 UTC, KirillKarpov commented on src/test/java/parser/JsonParserTestTestNG.java
> +    @Parameters({"path"})
@Parameter looks good as solution for 1 task (.. Exception test with >= 5 datasets).
I would like to ask you to write exception test with >= 5 datasets using @DataProvider from testNG

2020-10-14 20:20 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTestTestNG.java
> +    @Test(groups = {"checkintest"})
Added new Class testGroups with group names, replaced group names in annotations.

2020-10-14 20:20 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTestTestNG.java
> +        String path = "src\\main\\resources\\test-cart.json";
Fixed.

2020-10-14 20:21 UTC, olgamorozova1 commented on testng.xml
> +</suite>
Renamed.

2020-10-14 20:21 UTC, olgamorozova1 commented on testng3.xml
> +        <parameter name="path" value="src\main\resources\test-cart.json"/>
Fixed.

2020-10-14 20:21 UTC, olgamorozova1 commented on src/test/java/parser/JsonParserTestTestNG.java
> +    @Parameters({"path"})
Added new Exception test with data provider annotation.

2020-10-15 07:07 UTC, KirillKarpov approved these changes

2020-10-15 07:10 UTC, merged